// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: drivercommon/common.proto

package drivercommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IotPlatform int32

const (
	IotPlatform_LocalIot    IotPlatform = 0 //本地
	IotPlatform_CustomerIot IotPlatform = 1 //用户自定义
	IotPlatform_WinCLinkIot IotPlatform = 2 //赢创万联
	IotPlatform_AliIot      IotPlatform = 3 //阿里
	IotPlatform_HuaweiIot   IotPlatform = 4 //华为
	IotPlatform_TencentIot  IotPlatform = 5 //腾讯
	IotPlatform_TuyaIot     IotPlatform = 6 //涂鸦
	IotPlatform_OneNetIot   IotPlatform = 7 //中国移动
)

// Enum value maps for IotPlatform.
var (
	IotPlatform_name = map[int32]string{
		0: "LocalIot",
		1: "CustomerIot",
		2: "WinCLinkIot",
		3: "AliIot",
		4: "HuaweiIot",
		5: "TencentIot",
		6: "TuyaIot",
		7: "OneNetIot",
	}
	IotPlatform_value = map[string]int32{
		"LocalIot":    0,
		"CustomerIot": 1,
		"WinCLinkIot": 2,
		"AliIot":      3,
		"HuaweiIot":   4,
		"TencentIot":  5,
		"TuyaIot":     6,
		"OneNetIot":   7,
	}
)

func (x IotPlatform) Enum() *IotPlatform {
	p := new(IotPlatform)
	*p = x
	return p
}

func (x IotPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IotPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_drivercommon_common_proto_enumTypes[0].Descriptor()
}

func (IotPlatform) Type() protoreflect.EnumType {
	return &file_drivercommon_common_proto_enumTypes[0]
}

func (x IotPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IotPlatform.Descriptor instead.
func (IotPlatform) EnumDescriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{0}
}

type CloudInstanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloudInstanceId   string      `protobuf:"bytes,2,opt,name=cloudInstanceId,proto3" json:"cloudInstanceId,omitempty"`
	BaseAddress       string      `protobuf:"bytes,3,opt,name=baseAddress,proto3" json:"baseAddress,omitempty"`
	CloudInstanceName string      `protobuf:"bytes,4,opt,name=cloudInstanceName,proto3" json:"cloudInstanceName,omitempty"`
	IotPlatform       IotPlatform `protobuf:"varint,5,opt,name=iotPlatform,proto3,enum=drivercommon.IotPlatform" json:"iotPlatform,omitempty"`
}

func (x *CloudInstanceInfo) Reset() {
	*x = CloudInstanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivercommon_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloudInstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInstanceInfo) ProtoMessage() {}

func (x *CloudInstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_drivercommon_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInstanceInfo.ProtoReflect.Descriptor instead.
func (*CloudInstanceInfo) Descriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{0}
}

func (x *CloudInstanceInfo) GetCloudInstanceId() string {
	if x != nil {
		return x.CloudInstanceId
	}
	return ""
}

func (x *CloudInstanceInfo) GetBaseAddress() string {
	if x != nil {
		return x.BaseAddress
	}
	return ""
}

func (x *CloudInstanceInfo) GetCloudInstanceName() string {
	if x != nil {
		return x.CloudInstanceName
	}
	return ""
}

func (x *CloudInstanceInfo) GetIotPlatform() IotPlatform {
	if x != nil {
		return x.IotPlatform
	}
	return IotPlatform_LocalIot
}

type BaseRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseCloudPlatform  bool               `protobuf:"varint,1,opt,name=useCloudPlatform,proto3" json:"useCloudPlatform,omitempty"`
	CloudInstanceInfo *CloudInstanceInfo `protobuf:"bytes,2,opt,name=cloudInstanceInfo,proto3" json:"cloudInstanceInfo,omitempty"`
	DriverInstanceId  string             `protobuf:"bytes,3,opt,name=driverInstanceId,proto3" json:"driverInstanceId,omitempty"`
}

func (x *BaseRequestMessage) Reset() {
	*x = BaseRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivercommon_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequestMessage) ProtoMessage() {}

func (x *BaseRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_drivercommon_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequestMessage.ProtoReflect.Descriptor instead.
func (*BaseRequestMessage) Descriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequestMessage) GetUseCloudPlatform() bool {
	if x != nil {
		return x.UseCloudPlatform
	}
	return false
}

func (x *BaseRequestMessage) GetCloudInstanceInfo() *CloudInstanceInfo {
	if x != nil {
		return x.CloudInstanceInfo
	}
	return nil
}

func (x *BaseRequestMessage) GetDriverInstanceId() string {
	if x != nil {
		return x.DriverInstanceId
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Code         string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Success      bool   `protobuf:"varint,4,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivercommon_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivercommon_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommonResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommonResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivercommon_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_drivercommon_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_drivercommon_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivercommon_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_drivercommon_common_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_drivercommon_common_proto protoreflect.FileDescriptor

var file_drivercommon_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x11, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x73,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x69, 0x6f, 0x74, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x6f, 0x74, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x0b, 0x69, 0x6f, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x73,
	0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x75, 0x73, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x4d, 0x0a, 0x11, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x11, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49,
	0x64, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2b, 0x0a, 0x0f, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x84, 0x01, 0x0a, 0x0b, 0x49, 0x6f, 0x74, 0x50,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x49, 0x6f, 0x74, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x6f, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x57, 0x69, 0x6e, 0x43, 0x4c, 0x69,
	0x6e, 0x6b, 0x49, 0x6f, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x6c, 0x69, 0x49, 0x6f,
	0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x75, 0x61, 0x77, 0x65, 0x69, 0x49, 0x6f, 0x74,
	0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x49, 0x6f, 0x74,
	0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x75, 0x79, 0x61, 0x49, 0x6f, 0x74, 0x10, 0x06, 0x12,
	0x0d, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x4e, 0x65, 0x74, 0x49, 0x6f, 0x74, 0x10, 0x07, 0x32, 0x82,
	0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x12,
	0x42, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x69, 0x6e, 0x63, 0x2d, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x65, 0x64, 0x67, 0x65,
	0x2d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_drivercommon_common_proto_rawDescOnce sync.Once
	file_drivercommon_common_proto_rawDescData = file_drivercommon_common_proto_rawDesc
)

func file_drivercommon_common_proto_rawDescGZIP() []byte {
	file_drivercommon_common_proto_rawDescOnce.Do(func() {
		file_drivercommon_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_drivercommon_common_proto_rawDescData)
	})
	return file_drivercommon_common_proto_rawDescData
}

var file_drivercommon_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_drivercommon_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_drivercommon_common_proto_goTypes = []interface{}{
	(IotPlatform)(0),           // 0: drivercommon.IotPlatform
	(*CloudInstanceInfo)(nil),  // 1: drivercommon.CloudInstanceInfo
	(*BaseRequestMessage)(nil), // 2: drivercommon.BaseRequestMessage
	(*CommonResponse)(nil),     // 3: drivercommon.CommonResponse
	(*Pong)(nil),               // 4: drivercommon.Pong
	(*VersionResponse)(nil),    // 5: drivercommon.VersionResponse
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_drivercommon_common_proto_depIdxs = []int32{
	0, // 0: drivercommon.CloudInstanceInfo.iotPlatform:type_name -> drivercommon.IotPlatform
	1, // 1: drivercommon.BaseRequestMessage.cloudInstanceInfo:type_name -> drivercommon.CloudInstanceInfo
	6, // 2: drivercommon.Common.Ping:input_type -> google.protobuf.Empty
	6, // 3: drivercommon.Common.Version:input_type -> google.protobuf.Empty
	4, // 4: drivercommon.Common.Ping:output_type -> drivercommon.Pong
	5, // 5: drivercommon.Common.Version:output_type -> drivercommon.VersionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_drivercommon_common_proto_init() }
func file_drivercommon_common_proto_init() {
	if File_drivercommon_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_drivercommon_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloudInstanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drivercommon_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drivercommon_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drivercommon_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_drivercommon_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_drivercommon_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_drivercommon_common_proto_goTypes,
		DependencyIndexes: file_drivercommon_common_proto_depIdxs,
		EnumInfos:         file_drivercommon_common_proto_enumTypes,
		MessageInfos:      file_drivercommon_common_proto_msgTypes,
	}.Build()
	File_drivercommon_common_proto = out.File
	file_drivercommon_common_proto_rawDesc = nil
	file_drivercommon_common_proto_goTypes = nil
	file_drivercommon_common_proto_depIdxs = nil
}
